name = "ai-chat-worker"
main = "hono-worker.js"
compatibility_date = "2026-04-29"
workers_dev = true

[vars]
CHAT_ALLOWED_ORIGINS = "*"
DAILY_LIMIT = "5"
MAX_PROMPT_CHARS = "2000"
MAX_REPLY_CHARS = "4000"

[[d1_databases]]
binding = "DB"
database_name = "my-ai-db"
migrations_dir = "migrations"
# Your D1 database id (provided by user)
database_id = "573b4861-ab22-4480-97b0-8d53d3c05408"

